### PR TITLE
example files for generating ASTs

### PR DESCRIPTION
**Pull request by lea-hagen**
A couple folks have asked me for scripts/settings to generate lists of artificial stars.  Here's what I've been doing.  Feedback welcomed!  (can compare to production run grid here: https://github.com/BEAST-Fitting/beast/issues/322)

| parameters | number of points |
| --- | --- |
| log_age = [6.0, 10.13, 1.0] | 5 |
| Av = [0.01, 10.0, 0.5] | 20 |
| Rv = [2.0, 6.0, 1.0] | 5 |
| fA = [0.0, 1.0, 0.25] | 5 |
| log(Z) = -2.1, -1.5, -0.9, -0.3, 0.3 | 5 |

### CODE REVIEW

**Comment by lea-hagen** [comment]
See also the discussions of ASTs with subgrids in https://github.com/BEAST-Fitting/beast/issues/374 and https://github.com/BEAST-Fitting/beast/issues/489

**Comment by karllark** [comment]
Should I go ahead and merge?  Or do you want to update to include the distance prior?

**Comment by lea-hagen** [comment]
Adding the distance prior is quick, so I'll go ahead and do that.

**Comment by lea-hagen** [comment]
Should be good to merge now! (unless there are changes, of course)

**Review by karllark — APPROVED** [review]
Looks good.

**Pull request merged**
