### PR TITLE
Added source density binning parameters to the beast_settings file

### PR DESCRIPTION
**Pull request by cmurray-astro**
To keep things consistent across source density binning (for AST input generation, and later for splitting the observed and AST catalogs). This should be used to update the cached beast_settings file so the regression tests still work

### CODE REVIEW

**Review by karllark — COMMENTED** [review]
What if both variables are set?  Then what happens?

**Comment by karllark** [comment]
Ping.

**Comment by karllark** [comment]
And please update metal_small.  We are moving away from phat_small.  Thanks.

**Comment by cmurray-astro** [comment]
working on this! just made an erroneous update to the metal_small file... will fix

**Comment by cmurray-astro** [comment]
I added some more text to the explanation in the beast_settings.txt file in phat_small, to explain what happens when both parameters are set (it uses the bin width) and when neither are (it assumes integer binning from min to max source density). I also updated the metal_small beast_settings.txt file, which looks like it has no explanations in it for any parameters (and references phat_small). If we are moving away from phat_small, don't we want to keep the descriptions around?

**Comment by karllark** [comment]
Can you rebase/fix the conflicts?  Or should I attempt using the github online "resolve conflicts" button?

**Comment by cmurray-astro** [comment]
I'd try the "resolve conflicts" button :) it looks like a simple case for seeing how this works

**Comment by karllark** [comment]
Ping.

**Comment by cmurray-astro** [comment]
closed this in view of new PR (#24) to update metal_settings and stop updating phat_small

**Pull request closed without merging**
